name: 'YAML File Scanner'
description: 'Iterates over all files in a repository and posts YAML file contents to an HTTP endpoint'
inputs:
  scanner_api_url:
    description: 'Scanner.dev API URL'
    required: true
  scanner_api_key:
    description: 'Scanner.dev API key'
    required: true
  file_pattern:
    description: 'File pattern to match YAML files'
    required: false
    default: '**/*.yml'
runs:
  using: 'composite'
  steps:
    - name: Install scanner-cli
      shell: bash
      run: pip install --quiet scanner-cli
    - name: Run validation
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js
      env:
        INPUT_SCANNER_API_URL: ${{ inputs.scanner_api_url }}
        INPUT_SCANNER_API_KEY: ${{ inputs.scanner_api_key }}
        INPUT_FILE_PATTERN: ${{ inputs.file_pattern }}
branding:
  icon: 'file-text'
  color: 'blue'