name: Test Detection Rule Validator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install scanner-cli
        run: pip install scanner-cli
        
      - name: Test the action
        uses: ./
        with:
          scanner_api_base: '${{ secrets.SCANNER_API_BASE }}'
          scanner_api_key: '${{ secrets.SCANNER_API_KEY }}'
          file_pattern: 'tests/**/*.yml'