name: Test CLI Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install scanner-cli
        run: pip install scanner-cli
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Test the CLI action
        run: node index-cli.js
        env:
          INPUT_SCANNER_API_BASE: '${{ secrets.SCANNER_API_BASE }}'
          INPUT_SCANNER_API_KEY: '${{ secrets.SCANNER_API_KEY }}'
          INPUT_FILE_PATTERN: 'tests/**/*.yml'
          SCANNER_API_URL: '${{ secrets.SCANNER_API_BASE }}'
          SCANNER_API_KEY: '${{ secrets.SCANNER_API_KEY }}'